# Generated by Django 5.1.2 on 2024-10-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
        ('videos', '0002_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='account.profile'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
